feat: change to new api
101digital/adb-customer-support-sf-component pull request #7
Opened 2023-04-14 07:49 UTC by dungkm101digital

### Why

Change ticket system to use new api

Link to Jira ticket:
https://acsdigital.atlassian.net/browse/APB-712
https://acsdigital.atlassian.net/browse/APB-710
https://acsdigital.atlassian.net/browse/APB-883

2023-04-14 08:45 UTC, sk101dio requested changes
just remove that log, rest looks good.

2023-04-14 08:45 UTC, sk101dio commented on src/components/adb-create-ticket-details-component/index.tsx
> +                          console.log("readfFile catch: ", r);
remove this log.

2023-04-14 09:49 UTC, sk101dio approved these changes
looks good

2023-04-14 10:06 UTC, sharmal33 requested changes

2023-04-14 10:06 UTC, sharmal33 commented on src/common/constants.ts
> +  IN_PROGRESS = "In Progress",
this change will brake the existing flow which was implemented by Minh

2023-04-14 10:06 UTC, sharmal33 commented on src/components/adb-create-ticket-details-component/index.tsx
> +              if (response.serviceStatus === "SUCCESS") {
plz get these("SUCCESS") values from utils file

2023-04-17 02:53 UTC, dungkm101digital commented on src/common/constants.ts
> +  IN_PROGRESS = "In Progress",
Yes, this is the new api value.

2023-04-17 04:37 UTC, dungkm101digital commented on src/components/adb-create-ticket-details-component/index.tsx
> +              if (response.serviceStatus === "SUCCESS") {
I've added this function to utils file 
```js 
export function checkIfServiceStatusSuccess(response: CreateCaseResponse) {
    return response.serviceStatus === 'SUCCESS';
}
```

2023-04-17 06:02 UTC, sharmal33 approved these changes

2023-04-17 06:03 UTC, merged