feat: APB-710
101digital/adb-customer-support-sf-component pull request #8
Opened 2023-04-14 08:02 UTC by dungkm101digital

Info icon and modal ticket info

### Why

Add modal popup when press (i) icon

Link to Jira ticket: https://acsdigital.atlassian.net/browse/APB-710

2023-04-14 08:51 UTC, sk101dio requested changes
Please update accordingly.. rest looks good.

2023-04-14 08:51 UTC, sk101dio commented on src/components/adb-search-tickets-component/index.tsx
> +            <View style={{ flexDirection: "row", alignContent: "center" }}>
inline styling is prohibited...

2023-04-14 08:51 UTC, sk101dio commented on src/components/adb-search-tickets-component/index.tsx
> +                background={"#FFFFFF"}
use color constants instead of hex

2023-04-14 08:51 UTC, sk101dio commented on src/components/adb-search-tickets-component/index.tsx
> +                style={{ marginTop: 24 }}
no inline styling...

2023-04-14 08:51 UTC, sk101dio commented on src/components/adb-ticket-reminder-modal/index.tsx
> +    // paddingVertical: 24,
remove commented line

2023-04-14 09:51 UTC, sk101dio commented on src/components/adb-search-tickets-component/index.tsx
> +            <View style={}>
remove the empty styling

2023-04-14 09:56 UTC, sk101dio approved these changes

2023-04-14 10:00 UTC, sharmal33 requested changes

2023-04-14 10:00 UTC, sharmal33 commented on src/components/adb-ticket-reminder-modal/index.tsx
> +  "Tickets submitted past 5 PM will be processed the following day.",
plz move these to translations file

2023-04-14 10:08 UTC, dungkm101digital commented on src/components/adb-ticket-reminder-modal/index.tsx
> +  "Tickets submitted past 5 PM will be processed the following day.",
Can I just leave this here as default value?
And in aeon app, I will pass this as translated string?

2023-04-14 11:12 UTC, dungkm101digital commented on src/components/adb-ticket-reminder-modal/index.tsx
> +  "Tickets submitted past 5 PM will be processed the following day.",
I've make it to default props, in aeon app, user can pass-in ticketing system infomation to display as list

2023-04-18 07:21 UTC, sharmal33 requested changes

2023-04-18 07:48 UTC, dungkm101digital commented on src/components/adb-search-tickets-component/index.tsx
> +              asda
I mistype this

2023-04-19 01:24 UTC, merged